=== LidiyaLatysheva/JavaAutomation/Taxi/data/taxiStation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/taxiStation"
        xmlns:tns="http://www.example.com/taxiStation"
        elementFormDefault="qualified">

    <complexType name="Auto">
        <sequence>
            <element name="model" type="string"/>
            <element name="regNumber" type="tns:RegNumber"/>
            <element name="price" type="double"/>
            <element name="rentPrice" type="double"/>
        </sequence>
    </complexType>

    <simpleType name="RegNumber">
        <restriction>
            <pattern value="\d{4}[a-zA-Z]{2}[1-7]"/>
        </restriction>
    </simpleType>

    <complexType name="Car">
        <complexContent>
            <extension base="tns:Auto">
                <sequence>
                    <element name="passCount" type="int"/>
                    <element name="isBabySeatAvailable" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Minibus">
        <complexContent>
            <extension base="tns:Car">
                <sequence>
                    <element name="carrying" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Truck">
        <complexContent>
            <extension base="tns:Auto">
                <sequence>
                    <element name="carrying" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <element name="AUTO" type="tns:Auto" abstract="true"></element>
    <element name="CAR" type="tns:Car" substitutionGroup="tns:AUTO"></element>
    <element name="MINIBUS" type="tns:Minibus" substitutionGroup="tns:CAR"></element>
    <element name="TRUCK" type="tns:Truck" substitutionGroup="tns:AUTO"></element>

    <element name="taxiStation">
        <complexType>
            <sequence>
                <element ref="tns:AUTO" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

</schema>

=== LidiyaLatysheva/JavaAutomation/Taxi/data/taxiStation.xml
<?xml version="1.0" encoding="UTF-8"?>
<taxiStation xmlns="http://www.example.com/taxiStation"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.example.com/taxiStation taxiStation.xsd">
    <CAR>
        <model>Audi</model>
        <regNumber>0001AA1</regNumber>
        <price>24</price>
        <rentPrice>2</rentPrice>
        <passCount>4</passCount>
        <isBabySeatAvailable>true</isBabySeatAvailable>
    </CAR>
    <MINIBUS>
        <model>VW_Transporter</model>
        <regNumber>0002AA1</regNumber>
        <price>455</price>
        <rentPrice>20</rentPrice>
        <passCount>7</passCount>
        <isBabySeatAvailable>false</isBabySeatAvailable>
        <carrying>300</carrying>
    </MINIBUS>
    <TRUCK>
        <model>Kamaz</model>
        <regNumber>0003AA1</regNumber>
        <price>785</price>
        <rentPrice>400</rentPrice>
        <carrying>4000</carrying>
    </TRUCK>
    <CAR>
        <model>Audi</model>
        <regNumber>0004AA1</regNumber>
        <price>24</price>
        <rentPrice>2</rentPrice>
        <passCount>4</passCount>
        <isBabySeatAvailable>true</isBabySeatAvailable>
    </CAR>
    <MINIBUS>
        <model>VW_Transporter</model>
        <regNumber>0005AA1</regNumber>
        <price>455</price>
        <rentPrice>20</rentPrice>
        <passCount>7</passCount>
        <isBabySeatAvailable>false</isBabySeatAvailable>
        <carrying>300</carrying>
    </MINIBUS>
    <TRUCK>
        <model>Kamaz</model>
        <regNumber>0006AA1</regNumber>
        <price>785</price>
        <rentPrice>400</rentPrice>
        <carrying>4000</carrying>
    </TRUCK>
    <CAR>
        <model>Audi</model>
        <regNumber>0007AA1</regNumber>
        <price>24</price>
        <rentPrice>2</rentPrice>
        <passCount>4</passCount>
        <isBabySeatAvailable>true</isBabySeatAvailable>
    </CAR>
    <MINIBUS>
        <model>VW_Transporter</model>
        <regNumber>0008AA1</regNumber>
        <price>455</price>
        <rentPrice>20</rentPrice>
        <passCount>7</passCount>
        <isBabySeatAvailable>false</isBabySeatAvailable>
        <carrying>300</carrying>
    </MINIBUS>
    <TRUCK>
        <model>Kamaz</model>
        <regNumber>0009AA1</regNumber>
        <price>785</price>
        <rentPrice>400</rentPrice>
        <carrying>4000</carrying>
    </TRUCK>
    <CAR>
        <model>Audi</model>
        <regNumber>0010AA1</regNumber>
        <price>24</price>
        <rentPrice>2</rentPrice>
        <passCount>4</passCount>
        <isBabySeatAvailable>true</isBabySeatAvailable>
    </CAR>
    <MINIBUS>
        <model>VW_Transporter</model>
        <regNumber>0011AA1</regNumber>
        <price>455</price>
        <rentPrice>20</rentPrice>
        <passCount>7</passCount>
        <isBabySeatAvailable>false</isBabySeatAvailable>
        <carrying>300</carrying>
    </MINIBUS>
    <TRUCK>
        <model>Kamaz</model>
        <regNumber>0012AA1</regNumber>
        <price>785</price>
        <rentPrice>400</rentPrice>
        <carrying>4000</carrying>
    </TRUCK>
    <CAR>
        <model>Audi</model>
        <regNumber>0013AA1</regNumber>
        <price>24</price>
        <rentPrice>2</rentPrice>
        <passCount>4</passCount>
        <isBabySeatAvailable>false</isBabySeatAvailable>
    </CAR>
    <MINIBUS>
        <model>VW_Transporter</model>
        <regNumber>0014AA1</regNumber>
        <price>455</price>
        <rentPrice>20</rentPrice>
        <passCount>7</passCount>
        <isBabySeatAvailable>true</isBabySeatAvailable>
        <carrying>300</carrying>
    </MINIBUS>
    <TRUCK>
        <model>Kamaz</model>
        <regNumber>0015AA1</regNumber>
        <price>785</price>
        <rentPrice>400</rentPrice>
        <carrying>4000</carrying>
    </TRUCK>

</taxiStation>
